// Generated by CoffeeScript 1.9.3
(function() {
  if (window.Reader == null) {
    window.Reader = {};
  }

  window.Reader.Http = (function() {
    function Http(settings) {
      console.log('Http');
    }

    Http.prototype.getHTML = function(url, cb) {
      return $.get(url, function() {
        return cb();
      });
    };

    Http.prototype.getXML = function(url, cb) {
      return $.get(url, function() {
        return cb();
      });
    };

    return Http;

  })();

}).call(this);
