// Generated by CoffeeScript 1.9.3
(function() {
  if (window.Reader == null) {
    window.Reader = {};
  }

  window.Reader.Layout = (function() {
    function Layout() {
      console.log('Layout');
    }

    return Layout;

  })();

}).call(this);
