// Generated by CoffeeScript 1.9.3
(function() {
  if (window.Reader == null) {
    window.Reader = {};
  }

  window.Reader.Layout = (function() {
    function Layout(settings, spine) {
      this.settings = settings;
      this.spine = spine != null ? spine : {};
    }

    Layout.prototype.render = function() {
      return $.when(Reader.Http.prototype.get(this.settings.contentUrl, 'xml')).then((function(_this) {
        return function(data) {
          return _this.spine = Reader.Http.prototype.getSpine(data);
        };
      })(this)).then((function(_this) {
        return function(data) {
          var $spread, k, results, sectionPos, spreadCount, v;
          spreadCount = 0;
          sectionPos = 'left';
          $spread = null;
          results = [];
          for (k in data) {
            v = data[k];
            results.push(Reader.Http.prototype.get(v.href, 'html', function(section) {
              switch (sectionPos) {
                case 'left':
                  $spread = $('<article/>', {
                    'class': 'spread',
                    'data-idx': spreadCount
                  }).append($('<section/>', {
                    html: section
                  }));
                  break;
                case 'right':
                  if ($spread) {
                    $spread.append($('<section/>', {
                      html: section
                    }));
                  } else {
                    console.warn("Appending a right-hand section at position " + spreadCount + " to an empty article.");
                    $spread = $('<article/>', {
                      'class': 'spread',
                      'data-idx': spreadCount
                    }).append($('<section/>', {
                      html: section
                    }));
                  }
              }
              $(_this.settings.container).append($spread);
              ++spreadCount;
              return sectionPos = sectionPos === 'left' ? 'right' : 'left';
            }));
          }
          return results;
        };
      })(this));
    };

    return Layout;

  })();

}).call(this);
