// Generated by CoffeeScript 1.9.3
(function() {
  if (window.Reader == null) {
    window.Reader = {};
  }

  window.Reader.App = (function() {
    function App(options) {
      var defaults, settings;
      defaults = {
        contentUrl: null,
        spread: true,
        gutter: 0,
        viewport: {
          width: 468,
          height: 680
        },
        container: 'main',
        lazy: false,
        origin: {
          x: 0,
          y: 0
        }
      };
      settings = $.extend({}, defaults, options);
      this.isResizing = false;
      this.utils = new window.Reader.Utils;
      this.parse = new window.Reader.Parse;
      this.aspect = new window.Reader.Aspect(settings);
      this.layout = new window.Reader.Layout(settings);
      this.http = new window.Reader.Http;
      $((function(_this) {
        return function() {
          $.when(_this.layout.render()).then(function() {
            return $(document).trigger('reader.loaded');
          });
          $(document).on('reader.loaded', function() {
            return _this.aspect.setZoom();
          });
          return $(window).on({
            'resize': function() {
              _this.isResizing = true;
              return _this.utils.waitForFinalEvent((function() {
                _this.isResizing = false;
                _this.aspect.setZoom();
              }), 500, 'some unique string');
            }
          });
        };
      })(this));
    }

    return App;

  })();

}).call(this);
