// Generated by CoffeeScript 1.9.3
(function() {
  var Reader;

  Reader = (function() {
    function Reader(utils, aspect, http) {
      this.utils = utils;
      this.aspect = aspect;
      this.http = http;
      console.log('Main');
      this.settings = {
        spread: true,
        zoom: 1,
        viewport: null,
        resize: false,
        container: '#LB-Buch-Content-Def-1',
        origin: {
          x: 0,
          y: 0
        }
      };
      this.utils = new Utils;
      this.aspect = new Aspect(this.settings, this.utils);
      this.http = new Http(this.settings, this.utils);
      $((function(_this) {
        return function() {
          _this.aspect.getViewportValues();
          _this.aspect.setZoom();
          return $(window).on({
            'resize': function() {
              _this.settings.resize = true;
              return _this.utils.waitForFinalEvent((function() {
                _this.settings.resize = false;
                _this.aspect.setZoom();
              }), 500, 'some unique string');
            }
          });
        };
      })(this));
    }

    return Reader;

  })();

  if (typeof module !== "undefined" && module.exports) {
    exports.Reader = Reader;
  } else {
    window.Reader = Reader;
  }

}).call(this);
