// Generated by CoffeeScript 1.9.3
(function() {
  var Reader,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Reader = window.Reader != null ? window.Reader : window.Reader = {};

  Reader.Navbar = (function(superClass) {
    extend(Navbar, superClass);

    function Navbar(settings, elem) {
      this.settings = settings;
      this.elem = elem != null ? elem : $(this.settings.innerContainer);
    }

    Navbar.prototype.append = function() {
      return console.log($('body').append(this.navbar));
    };

    return Navbar;

  })(Reader);

}).call(this);
