// Generated by CoffeeScript 1.9.3
<<<<<<< HEAD
(function() {
  var Utils;

  Utils = (function() {
    function Utils() {}
=======
var Utils;

Utils = (function() {
  function Utils() {}
>>>>>>> dd854c4ee057fb2546a520b2d238d7e786243655

  Utils.prototype.prefix = (function() {
    var dom, pre, styles;
    styles = window.getComputedStyle(document.documentElement, '');
    pre = (Array.prototype.slice.call(styles).join('').match(/-(moz|webkit|ms)-/) || styles.OLink === '' && ['', 'o'])[1];
    dom = 'WebKit|Moz|MS|O'.match(new RegExp('(' + pre + ')', 'i'))[1];
    return {
      dom: dom,
      lowercase: pre,
      css: '-' + pre + '-',
      js: pre[0].toUpperCase() + pre.substr(1)
    };
  })();

  Utils.prototype.waitForFinalEvent = (function() {
    var timers;
    timers = {};
    return function(callback, ms, uniqueId) {
      if (!uniqueId) {
        uniqueId = 'Don\'t call this twice without a uniqueId';
      }
      if (timers[uniqueId]) {
        clearTimeout(timers[uniqueId]);
      }
      timers[uniqueId] = setTimeout(callback, ms);
    };
  })();

  return Utils;

})();

if (window.Reader == null) {
  window.Reader = {};
}

<<<<<<< HEAD
  if (window.Reader == null) {
    window.Reader = {};
  }

  window.Reader.Utils = Utils;

}).call(this);
=======
window.Reader.Utils = Utils;
>>>>>>> dd854c4ee057fb2546a520b2d238d7e786243655
